# Site Build Settings
production_url: https://lazysecurity.xyz
url: https://lazysecurity.xyz
# jekyll-paginate configuration
paginate: 5

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title
timezone: Europe/Moscow
plugins: [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title: "Lazy Security Blog"
description: "a minimalist Jekyll theme for running a blog or publication"
author: "L4zy"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
path: rss-feed.xml
